@HostAddress = http://localhost:5277

GET {{HostAddress}}/openapi/v1.json

###

GET {{HostAddress}}/api/catalog/types
accept: application/json

###

GET {{HostAddress}}/api/catalog/brands
accept: application/json

###

GET {{HostAddress}}/api/catalog/items
accept: application/json

###

GET {{HostAddress}}/api/catalog/items?type=1&brand=1

###

# A request with an unknown item id returns a 404 NotFound with empty response body

GET {{HostAddress}}/api/catalog/items/463

###

# Invalid - name is missing

POST {{HostAddress}}/api/catalog/items
content-type: application/json

{
  "id": 421,
  "price": 100,
  "description": "Description1",
  "pictureFileName": "item421.png",
  "catalogTypeId": 1,
  "catalogBrandId": 2
}

